### ISSUE TITLE
CaH breaks after shuffling cards

### ISSUE THREAD

**Issue by astravexton** [tetrapus/Karkat#89]
http://bin.zyr.io/72dD1vYdFL.txt
http://bin.zyr.io/VuC2Nustof.txt

**Comment by tetrapus** [comment]
Is this on HEAD? See #81, CAH on HEAD is broken, might want to reset the
file to that commit and patch on stable

**Comment by nathan0** [comment]
yeah it is on HEAD, `card` ends up as a list which causes the TypeError
